version: '3'

services: 
  Etcd:
    container_name: toma-etcd
    image: bitnami/etcd:latest
    environment: 
      - ALLOW_NONE_AUTHENTICATION=yes
    #  - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-server:2379
    privileged: true
    # volumes:
    # ./etcd/data:/bitnami/etcd/data
    ports: 
      - 2379:2379
      - 2380:2380